---

- hosts: loadbalancer
  become: true
  tasks:
    - name: Install nginx on ubuntu
      apt: name='nginx' state=present
    - name: Start nginx server
      service: name='nginx' state=started enabled=true
    - name: copy nginx.cfg to the nginx server
      copy: src=nginx.cfg dest=/etc/nginx/nginx.conf
      notify: restart nginx server

  handlers:
    - name: restart nginx server
      service: name='nginx' state='restarted'
