---

- hosts: webservers
  become: true
  tasks:
    - name: Install git
      yum: name='git' state=present
    - name: Install apache server on centos
      yum: name='httpd' state=present
    - name: Start apache server
      service: name='httpd' state=started enabled=true
    - name: clone website from git repo
      git:
        repo: https://github.com/javahometech/website-ansble
        dest: /var/www/html
